# Generated by Django 5.1.6 on 2026-01-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('land_area', models.CharField(max_length=50)),
                ('land_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
