# Generated by Django 5.1.6 on 2026-01-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_claim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Forwarded', 'Forwarded')], default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
